[project]
name = "scripts"
version = "0.0.1"
description = "Scripts to assist with development of Deskflow"
requires-python = ">=3.9"
dependencies = [
  "clang-format",
  "python-dotenv",
  "pyyaml",
  "colorama",
  "gitpython",
  "psutil",
]
